import math

import bpy
from ..debug.log import scene


RIG_CHAIN = (
    ("LIMN_TRACK_CTRL", "CUBE", 1.0),
    ("LIMN_SWING_CTRL", "SINGLE_ARROW", 0.9),
    ("LIMN_BOOM_CTRL", "SINGLE_ARROW", 0.9),
    ("LIMN_EXTENSION_CTRL", "PLAIN_AXES", 0.8),
    ("LIMN_PAN_CTRL", "CIRCLE", 0.55),
    ("LIMN_TILT_CTRL", "CIRCLE", 0.45),
    ("LIMN_ROLL_CTRL", "CIRCLE", 0.35),
)


def ensure_empty(name, col, display, size):
    obj = bpy.data.objects.get(name)

    if obj is None:
        scene("Creating rig control:", name)
        obj = bpy.data.objects.new(name, None)
        obj.empty_display_type = display
        obj.empty_display_size = size
        obj.show_name = False
        col.objects.link(obj)
    elif obj.name not in col.objects:
        col.objects.link(obj)

    return obj


def ensure_rig_controls(root, cam, col):
    """
    Ensure the persistent LIMNMOCO rig hierarchy exists.

    The hierarchy is authoritative. Meshes and curves generated by
    visual layers can be deleted and rebuilt; these controls survive.
    """

    controls = {}
    parent = root

    for name, display, size in RIG_CHAIN:
        obj = ensure_empty(name, col, display, size)
        obj.parent = parent
        controls[name] = obj
        parent = obj

    cam.parent = controls["LIMN_ROLL_CTRL"]
    return controls


def set_local_transform(obj, location=(0, 0, 0), rotation=(0, 0, 0)):
    obj.location = location
    obj.rotation_euler = rotation
    obj.scale = (1, 1, 1)


def drive_rig_controls(controls, cam, result, props):
    """
    Drive persistent rig controls from the solver result.

    Track, swing, boom, extension, pan, tilt, roll, and nodal offset are
    represented in the parented control chain. The camera follows that
    hierarchy instead of being assigned a solved world transform.
    """

    scene("drive_rig_controls()")

    swing_rad = math.radians(result.swing_deg)
    boom_rad = math.radians(result.boom_deg)

    set_local_transform(
        controls["LIMN_TRACK_CTRL"],
        location=(0, result.track, 0),
    )
    set_local_transform(
        controls["LIMN_SWING_CTRL"],
        rotation=(0, 0, -swing_rad),
    )
    set_local_transform(
        controls["LIMN_BOOM_CTRL"],
        rotation=(boom_rad, 0, 0),
    )
    set_local_transform(
        controls["LIMN_EXTENSION_CTRL"],
        location=(0, props.boom_length, 0),
        rotation=(-boom_rad, 0, 0),
    )
    set_local_transform(
        controls["LIMN_PAN_CTRL"],
        location=(0, props.extension_length, 0),
        rotation=(0, 0, math.radians(props.vpan)),
    )
    set_local_transform(
        controls["LIMN_TILT_CTRL"],
        rotation=(math.radians(props.vtilt), 0, 0),
    )
    set_local_transform(
        controls["LIMN_ROLL_CTRL"],
        rotation=(0, math.radians(props.vroll), 0),
    )

    set_local_transform(
        cam,
        location=(props.offset_x, props.offset_y, props.offset_z),
        rotation=(math.radians(90), 0, 0),
    )


def parent_to_rig_local(obj, parent):
    if obj is None or parent is None or obj == parent:
        return

    obj.parent = parent


def parent_generated_visuals(col, root, controls):
    """
    Parent disposable visualization objects under the rig root.

    Generated visual objects are drawn in rig-local coordinates. Keeping
    them under the root makes LIMNMOCO_RIG_ROOT the scene placement
    object without making the visuals authoritative.
    """

    persistent = {root.name, "LIMN_CONTROL", "LIMN_CAMERA"}
    persistent.update(ctrl.name for ctrl in controls.values())

    for obj in list(col.objects):
        if obj.name in persistent:
            continue

        parent_to_rig_local(obj, root)
