import math

import bpy

from ..core.transforms import blender_camera_rotation_from_virtual_matrix
from ..debug.log import scene


RIG_CHAIN = (
    ("LIMN_TRACK_CTRL", "CUBE", 1.0),
    ("LIMN_SWING_CTRL", "SINGLE_ARROW", 0.9),
    ("LIMN_BOOM_CTRL", "SINGLE_ARROW", 0.9),
    ("LIMN_EXTENSION_CTRL", "PLAIN_AXES", 0.8),
    ("LIMN_PAN_CTRL", "CIRCLE", 0.55),
    ("LIMN_TILT_CTRL", "CIRCLE", 0.45),
    ("LIMN_ROLL_CTRL", "CIRCLE", 0.35),
)


def ensure_empty(name, col, display, size):
    obj = bpy.data.objects.get(name)

    if obj is None:
        scene("Creating rig control:", name)
        obj = bpy.data.objects.new(name, None)
        obj.empty_display_type = display
        obj.empty_display_size = size
        obj.show_name = False
        col.objects.link(obj)
    elif obj.name not in col.objects:
        col.objects.link(obj)

    return obj


def ensure_rig_controls(root, cam, col):
    """
    Ensure the persistent LIMNMOCO rig hierarchy exists.

    The hierarchy is authoritative. Meshes and curves generated by
    visual layers can be deleted and rebuilt; these controls survive.
    """

    controls = {}
    parent = root

    for name, display, size in RIG_CHAIN:
        obj = ensure_empty(name, col, display, size)
        obj.parent = parent
        controls[name] = obj
        parent = obj

    cam.parent = controls["LIMN_ROLL_CTRL"]
    return controls


def set_local_transform(obj, location=(0, 0, 0), rotation=(0, 0, 0)):
    obj.location = location
    obj.rotation_euler = rotation


def drive_rig_controls(controls, cam, result, props):
    """
    Drive persistent rig controls from the solver result.

    Track, swing, boom, extension, and nodal offset are represented in
    the parented control chain. The camera keeps the final solved
    Blender orientation so it remains visually correct while the rig
    hierarchy carries the mechanical solve.
    """

    scene("drive_rig_controls()")

    swing_rad = math.radians(result.swing_deg)
    boom_rad = math.radians(result.boom_deg)

    set_local_transform(
        controls["LIMN_TRACK_CTRL"],
        location=(0, result.track, 0),
    )
    set_local_transform(
        controls["LIMN_SWING_CTRL"],
        rotation=(0, 0, -swing_rad),
    )
    set_local_transform(
        controls["LIMN_BOOM_CTRL"],
        rotation=(boom_rad, 0, 0),
    )
    set_local_transform(
        controls["LIMN_EXTENSION_CTRL"],
        location=(0, props.boom_length, 0),
    )
    set_local_transform(
        controls["LIMN_PAN_CTRL"],
        location=(0, props.extension_length, 0),
        rotation=(0, 0, math.radians(props.vpan)),
    )
    set_local_transform(
        controls["LIMN_TILT_CTRL"],
        rotation=(math.radians(props.vtilt), 0, 0),
    )
    set_local_transform(
        controls["LIMN_ROLL_CTRL"],
        rotation=(0, math.radians(props.vroll), 0),
    )

    camera_rotation = blender_camera_rotation_from_virtual_matrix(
        result.rotation
    )
    camera_world = camera_rotation.to_4x4()
    camera_world.translation = result.nodal
    cam.matrix_world = camera_world


def parent_keep_world(obj, parent):
    if obj is None or parent is None or obj == parent:
        return

    obj.parent = parent
    obj.matrix_parent_inverse = parent.matrix_world.inverted()


def parent_generated_visuals(col, root, controls):
    """
    Parent disposable visualization objects under the relevant rig controls.
    """

    layer_parents = (
        ("CRANE_MECH_TrackRail", controls["LIMN_TRACK_CTRL"]),
        ("CRANE_MECH_BaseCarriage", controls["LIMN_TRACK_CTRL"]),
        ("CRANE_MECH_SwingColumn", controls["LIMN_SWING_CTRL"]),
        ("CRANE_MECH_BoomArm", controls["LIMN_BOOM_CTRL"]),
        ("CRANE_MECH_ExtensionArm", controls["LIMN_EXTENSION_CTRL"]),
        ("CRANE_MECH_PanHead", controls["LIMN_PAN_CTRL"]),
        ("CRANE_MECH_CameraBlock", controls["LIMN_ROLL_CTRL"]),
        ("CRANE_MECH_PanHead_to_CameraBlock", controls["LIMN_PAN_CTRL"]),
        ("CAM_", controls["LIMN_ROLL_CTRL"]),
        ("RANGE_", root),
        ("ENVELOPE_", root),
        ("TARGET", root),
        ("BASE", controls["LIMN_TRACK_CTRL"]),
        ("ArmTip", controls["LIMN_BOOM_CTRL"]),
        ("PAN Center", controls["LIMN_PAN_CTRL"]),
        ("Camera Nodal", controls["LIMN_ROLL_CTRL"]),
        ("BOOM", controls["LIMN_BOOM_CTRL"]),
        ("CRANE_LevelExtension", controls["LIMN_EXTENSION_CTRL"]),
        ("CameraOffset", controls["LIMN_PAN_CTRL"]),
        ("Error", root),
        ("AXIS", root),
    )

    persistent = {root.name, "LIMN_CONTROL", "LIMN_CAMERA"}
    persistent.update(ctrl.name for ctrl in controls.values())

    for obj in list(col.objects):
        if obj.name in persistent:
            continue

        parent = root

        for prefix, target_parent in layer_parents:
            if obj.name.startswith(prefix):
                parent = target_parent
                break

        parent_keep_world(obj, parent)
